-- create table
-- CREATE TABLE euphoria_users (
--     id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
--     fullname TEXT NOT NULL,
--     username TEXT NOT NULL,
--     password TEXT NOT NULL
-- );

CREATE TABLE blog (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    username TEXT NOT NULL
)