/*-- remove table is it exists
drop table if exists euphoria_users;

-- create table
CREATE TABLE euphoria_users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    fullname TEXT NOT NULL,
    username TEXT NOT NULL,
    password TEXT NOT NULL
);

--insert test data
insert into euphoria_users (fullname, username, password)
values
    ('Bob Builder', 'BBuild1', 'Marysays29901'),
    ('Joan Lynn', 'JJoles3', 'candylady2'),
    ('Bill Wet', 'Twilight_1', 'Wolfpack112')*/

BEGIN;

TRUNCATE
  euphoria_users
  RESTART IDENTITY CASCADE;

INSERT INTO euphoria_users (fullname, username, password)
VALUES
    ('Bob Builder', 'BBuild1', 'Marysays29901'),
    ('Joan Lynn', 'JJoles3', 'candylady2'),
    ('Bill Wet', 'Twilight_1', 'Wolfpack112');

COMMIT;